"""users table

Revision ID: 94c94daff4be
Revises: 2777df7e02ca
Create Date: 2020-02-27 22:35:53.582633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94c94daff4be'
down_revision = '2777df7e02ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('type_quantity', sa.Boolean(), nullable=True))
    op.add_column('ingredient', sa.Column('type_volume', sa.Boolean(), nullable=True))
    op.add_column('ingredient', sa.Column('type_weight', sa.Boolean(), nullable=True))
    op.drop_column('ingredient', 'weight')
    op.drop_column('ingredient', 'volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('volume', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('ingredient', sa.Column('weight', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('ingredient', 'type_weight')
    op.drop_column('ingredient', 'type_volume')
    op.drop_column('ingredient', 'type_quantity')
    # ### end Alembic commands ###
