"""users table

Revision ID: a49fe44a7aee
Revises: c7dcf8e5a878
Create Date: 2020-03-21 16:47:56.648885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49fe44a7aee'
down_revision = 'c7dcf8e5a878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quantity', type_='foreignkey')
    op.create_foreign_key(None, 'quantity', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quantity', type_='foreignkey')
    op.create_foreign_key(None, 'quantity', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
