"""users table

Revision ID: c7dcf8e5a878
Revises: 
Create Date: 2020-03-15 12:39:30.074615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dcf8e5a878'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('food_group', sa.String(length=180), nullable=True),
    sa.Column('food_subgroup', sa.String(length=180), nullable=True),
    sa.Column('food_type', sa.String(length=180), nullable=True),
    sa.Column('type_quantity', sa.Boolean(), nullable=True),
    sa.Column('type_volume', sa.Boolean(), nullable=True),
    sa.Column('type_weight', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=140), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.Enum('teaspoon', 'tablespoon', 'fluid_ounce', 'cup', 'pint', 'quart', 'gallon', 'milliliter', 'liter', 'deciliter', 'pound', 'ounce', 'milligram', 'gram', 'kilogram', 'quantity', name='unittypesenum'), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantity')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
